language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sroy102024/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sroy102024/react-test npm test -- --coverage

after_success:
  - docker build -t sroy102024/multi-client ./client
  - docker build -t sroy102024/multi-nginx ./nginx
  - docker build -t sroy102024/multi-server ./server
  - docker build -t sroy102024/multi-worker ./worker
